### ISSUE TITLE
Mobile recipe type facet has a minor lay-out issue

### ISSUE THREAD

**Issue by MPParsley** [nickveenhof/drupal8-umami-search#13]
![screenshot_20180708-222653_samsung internet](https://user-images.githubusercontent.com/1823998/42423696-0a5a7c1c-82ff-11e8-9914-7906ae1a4dc6.jpg)

**Comment by nickveenhof** [comment]
Pull request #20 seems to fix this.

**Comment by MPParsley** [comment]
Indeed, this is now fixed.

<img width="353" alt="recipe" src="https://user-images.githubusercontent.com/1823998/46946235-6345bb00-d077-11e8-8517-4747a3dc8836.png">
