### ISSUE TITLE
[Feature request] Add spellcheck

### ISSUE THREAD

**Issue by MPParsley** [nickveenhof/drupal8-umami-search#15]
We already provide suggestions (search_api_autocomplete) but perhaps it could be useful to also add the spellcheck project?

[Drupal project page] https://www.drupal.org/project/search_api_spellcheck
[Drupal 8 port on GitHub] https://github.com/nuvoleweb/search_api_spellcheck
[Deprecated sandbox?] http://cgit.drupalcode.org/sandbox-rupertj-2766155/log/?h=8.x-1.x

**Comment by borisson** [comment]
The spellcheck project seems to be targetted at using solr as a backend, for now. we're using db - so we can't do this.

**Comment by MPParsley** [comment]
Right, didn't take that into account.
