### ISSUE TITLE
Configure views caching

### ISSUE THREAD

**Issue by MPParsley** [nickveenhof/drupal8-umami-search#21]
At the moment caching is set to `none` for [search api view](http://drupalsear.ch/admin/structure/views/view/search), this should be set to `Search API (tag-based)`.

<img width="478" alt="caching disabled" src="https://user-images.githubusercontent.com/1823998/46287342-8bff8800-c582-11e8-9cd0-eaf5dd697bb2.png">

**Comment by nickveenhof** [comment]
+ we should also enable ajax, to show the full scope. This is something for tomorrow

**Comment by nickveenhof** [comment]
Done!
