### ISSUE TITLE
Only one range slider facet is working

### ISSUE THREAD

**Issue by MPParsley** [nickveenhof/drupal8-umami-search#24]
<img width="322" alt="range" src="https://user-images.githubusercontent.com/1823998/46946318-95efb380-d077-11e8-993d-665a68e6fee5.png">

<img width="318" alt="servings" src="https://user-images.githubusercontent.com/1823998/46946397-e109c680-d077-11e8-8c88-6cb08a17d76e.png">

On http://drupalsear.ch/search only one of the range sliders is working.

**Comment by nickveenhof** [comment]
Updated the drupalsearch site and both sliders are working as expected
