### ISSUE TITLE
Invalid Password

### ISSUE THREAD

**Issue by bajahranks** [nickveenhof/drupal8-umami-search#28]
The username and password displayed at the top of the drupalsear.ch website, which I believe corresponds to this Github project isn't working. 

I would love to see how the configurations are implemented.

Thank you.

**Comment by MPParsley** [comment]
The account was probably locked.

The site is reinstalled every 30 minutes, you should be able to login with username and password drupalsearch in 30 minutes.

**Comment by bajahranks** [comment]
I was able to get in but it looks like all the content was erased. I suppose some maintenance is being done at the moment. I'll try again later.

**Comment by Rufus13apostol** [comment]
Hi there,

Where exactly are the credentials? Cannot find them anywhere int the example site...

cheers

**Comment by nickveenhof** [comment]
Fixed in latest master. The install script no longer had the password/username included
