### ISSUE TITLE
The highlight processor doesn't seem to handle caches properly

### ISSUE THREAD

**Issue by MPParsley** [nickveenhof/drupal8-umami-search#9]
Steps to reproduce:
- query for "garlic" - http://drupalsear.ch/search?query=garlic => garlic is highlighted
- quary for "quiche" - http://drupalsear.ch/search?query=quiche => garlic is still highlighted

**Comment by nickveenhof** [comment]
This should be reported to search_api @ drupal.org. @borisson / @StryKaizer are also informed of this.

**Comment by MPParsley** [comment]
See https://www.drupal.org/project/search_api/issues/2983640

**Comment by nickveenhof** [comment]
Fixed!
